blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.HomeView.as_view(), name="homepage"),
    path("search/", views.PostSearchView.as_view(), name='post_search'),
    path("<slug:post>/", views.post_single, name='post_single'),
    path("tag/<slug:tag>/", views.TagListView.as_view(), name='post_by_tag')

]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("blog.urls")),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.urls import reverse


# Create your models here.
class Post(models.Model):
    options = (
        ("draft", "Draft"),
        ("published", "Published"),
    )

    title = models.CharField(max_length=250)
    subtitle = models.CharField(max_length=100)
    slug = models.SlugField(max_length=250, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="post_author"
    )
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=options, default="draft")

    tags = TaggableManager()

    def get_absolute_url(self):
        return reverse('post_single', args=[self.slug])

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from blog.models import Post


class PostSearchForm(forms.Form):
    q = forms.CharField()

    def __int__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['q'].widget.attrs.update({'class': 'form-control'})


class PostForm(forms.Form):
    class Meta:
        model = Post

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from .models import Post
from blog.forms import PostSearchForm


# Create your views here.
class HomeView(ListView):
    model = Post
    #    template_name = "blog/index.html"
    context_object_name = "posts"
    paginate_by = 10

    def get_template_names(self):
        if self.request.htmx:
            return "components/post-list-elements.html"
        return "blog/index.html"


def post_single(request, post):
    post = get_object_or_404(Post, slug=post, status='published')
    related = Post.objects.filter(author=post.author)[:5]
    return render(request, 'blog/single.html', {'post': post, 'related': related})


class TagListView(ListView):
    model = Post
    paginate_by = 10
    context_object_name = 'posts'

    def get_queryset(self):
        x = Post.objects.filter(status__exact='published', tags__name__in=[self.kwargs['tag']])
        return x

    def get_template_names(self):
        if self.request.htmx:
            return "components/post-list-elements-tags.html"
        return 'blog/tags.html'

    def get_context_data(self, **kwargs):
        context = super(TagListView, self).get_context_data(**kwargs)
        context['tag'] = self.kwargs['tag']

        return context


class PostSearchView(ListView):
    model = Post
    paginate_by = 10
    context_object_name = 'posts'
    form_class = PostSearchForm

    def get_queryset(self):
        form = self.form_class(self.request.GET)  # grab data from form
        if form.is_valid():
            return Post.objects.filter(status__exact='published', title__icontains=form.cleaned_data['q'])
        return []

    def get_template_names(self):
        if self.request.htmx:
            return "components/post-list-elements-search.html"
        return 'blog/search.html'

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load tag_cloud %}
{% block title %}Index page{% endblock %}

{% block template %}
    {% include 'navbar.html' %}
    {% include 'components/splash.html' %}

    <div class="container pt-5">
        <div class="row">
            <div class="col-12 col-lg-8">
                {% include 'components/post-list-elements.html' %}
            </div>
            <div class="d-none d-lg-block col-4">

                {% load tag_cloud %}
                {% sidebar_tag_cloud %}

                {% include 'footer.html' %}
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/search.html
{% extends '3-col-template.html' %}

{% block content-left %}
    {% include 'secondary-navbar.html' %}
{% endblock %}

{% block content-mid %}
    <div class="center mx-auto" style="max-width: 683px">
        <h1 class="fs-1 fw-bold pb-5">
            {% if posts %}
                <span class="text-muted">Results for: </span>{{ request.GET.q }}
            {% else %}
                <span>Try again</span>
            {% endif %}
        </h1>
        {% include 'components/post-list-elements-search.html' %}
        {% if not posts %}
            <div class="col-12">Try searching for something else!</div>
        {% endif %}
    </div>
{% endblock %}

{% block content-right %}
    {% sidebar_tag_cloud %}
{% endblock %}

blog/templates/blog/single.html
{% extends "3-col-template.html" %}

{% block content-left %}
    {% include "secondary-navbar.html" %}
{% endblock %}

{% block content-mid %}
    <style>
        .blogger h1 {
            letter-spacing: -0.6px;
        }

        .post h1 {
            font-size: 24px;
            font-weight: bold;
        }

        .post p {
            font-family: Merriweather;
            font-size: 1.0625rem;
            line-height: 32px;
            letter-spacing: 0.2px;
        }
    </style>
    <div class="blogger center mx-auto" style="max-width: 683px">
        <div class="text-muted">{{ post.author }}</div>
        <div class="text-muted pb-5">{{ post.updated_at|date:"d, M, Y" }}</div>
        <h1 class="fw-bold pb-2">{{ post.title }}</h1>
        <h2 class="text-muted fs-4 pb-2">{{ post.subtitle }}</h2>
        <div class="post">
            {{ post.content | markdown | safe }}
        </div>
    </div>
{% endblock %}

{% block content-right %}
    {% sidebar_tag_cloud %}
    <div class="col-12">
        <div class="pb-3">More from {{ post.author }}</div>
        {% for post in related %}
            <a class="text-decoration-none" href="{{ post.get_absolute_url }}">
                <div class="card mb-3 border-0 ps-1 color">
                    <div class="row">
                        <div class="col-9 pe-2">
                            <span class="text-dark small">{{ post.author }}</span>
                            <h1 class="mb-1 fs-6 p-0 text-dark fw-bold">{{ post.title|truncatechars:80 }}</h1>
                        </div>
                        <div class="col-3">
                            <img src="https://picsum.photos/205/115" class="img-fluid float-end" alt="img">
                        </div>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/tags.html
{% extends '3-col-template.html' %}

{% block content-left %}
    {% include 'secondary-navbar.html' %}
{% endblock %}

{% block content-mid %}
    <div class="center mx-auto" style="max-width: 683px">
        <h1 class="fs-1 fw-bold pb-5">{{ tag|title }}</h1>
        {% include 'components/post-list-elements-tags.html' %}
    </div>
{% endblock %}

{% block content-right %}
    {% sidebar_tag_cloud %}
{% endblock %}

blog/templates/components/post-list-elements-search.html
<style>
    p {
        font-family: 'Merriweather', sans-serif;
        line-height: 22px;
    }

</style>

{% for post in posts %}

    <a href="{{ post.get_absolute_url }}" class="text-decoration-none">
    {% if forloop.last and page_obj.has_next %}
        <div class="card border-0 pb-3 pb-sm-5 color" hx-get="{{ request.get_full_path }}&page={{ page_obj.number|add:1 }}"
             hx-trigger="revealed" hx-swap="afterend">
    {% else %}
        <div class="card border-0 pb-3 pb-sm-5 color">
    {% endif %}
        <div class="row">
            <div class="col-9">
                <div class="card-body p-0">
                    <div class="pb-2 text-body infscroll-author small">{{ post.author }}</div>
                    <h1 class="mb-1 text-body fw-bold infscroll-title">{{ post.title|truncatechars:80 }}</h1>
                    <p class="d-none d-sm-block fs-14 text-dark">{{ post.content|truncatechars:180 }}</p>
                </div>
            </div>
            <div class="col-3">
                <img src="https://picsum.photos/205/115" class="img-fluid float-end" alt="img">
            </div>
        </div>
        </div>
    </a>
{% endfor %}

blog/templates/components/post-list-elements-tags.html
<style>
    p {
        font-family: 'Merriweather', sans-serif;
        line-height: 22px;
    }

</style>

{% for post in posts %}
    <a href="{{ post.get_absolute_url }}" class="text-decoration-none">
        {% if forloop.last and page_obj.has_next %}
            <div class="card border-0 pb-3 pb-sm-5 color" hx-get="{{ request.path }}?page={{ page_obj.number|add:1 }}"
                 hx-trigger="revealed" hx-swap="afterend">
        {% else %}
            <div class="card border-0 pb-3 pb-sm-5 color">
        {% endif %}
        <div class="row">
            <div class="col-9">
                <div class="card-body p-0">
                    <div class="pb-2 text-body infscroll-author small">{{ post.author }}</div>
                    <h1 class="mb-1 text-body fw-bold infscroll-title">{{ post.title|truncatechars:80 }}</h1>

                    <p class="d-none d-sm-block fs-14 text-dark">{{ post.content|truncatechars:180 }}</p>

                </div>
            </div>
            <div class="col-3">
                <img src="https://picsum.photos/205/115" class="img-fluid float-end" alt="img">
            </div>
        </div>
        </div>
    </a>
{% endfor %}

blog/templates/components/post-list-elements.html
{% for post in posts %}
    <a href="{{ post.get_absolute_url }}" class="text-decoration-none">
    {% if forloop.last and page_obj.has_next %}
        <div class="card border-0 pb-3 pb-sm-5 color" hx-get="{{ request.path }}?page={{ page_obj.number|add:1 }}"
             hx-trigger="revealed" hx-swap="afterend">
    {% else %}

        <div class="card border-0 pb-3 pb-sm-5 color">
    {% endif %}
        <div class="row">
            <div class="col-9">
                <div class="card-body p-0">
                    <div class="pb-2 text-body infscroll-author small">{{ post.author }}</div>
                    <h1 class="mb-1 text-body fw-bold infscroll-title">{{ post.title|truncatechars:80 }}</h1>
                    <p class="d-none d-sm-block fs-14 text-dark">{{ post.content|truncatechars:180 }}</p>
                </div>
            </div>
            <div class="col-3">
                <img src="https://picsum.photos/205/115" class="img-fluid float-end" alt="img">
            </div>
        </div>
        </div>
    </a>
{% endfor %}

blog/templates/components/search-bar.html
<form method="get" action="/search/" class="col-12 pb-5">
    <input type="text" name="q" id="id_q" class="form-control rounded-pill" placeholder="Search..">
</form>

blog/templates/components/splash.html
<div class="border-bottom border-1 border-dark">
    <div class="container py-5">

        <div class="row">
            <div class="col-12 col-md-6 py-1 py-md-5 text-center text-md-start">
                <h1 class="display-2">Tech Talk.</h1>
                <p class="fs-4 lh-1 text-muted fw-bolder fw-500 pb-4">
                    No nonsense tutorials, tips, and expertise from writers on tech topics.
                </p>
                <button class="btn btn-dark rounded-pill fw-500 fs-5 px-4" type="button">Start reading</button>
            </div>
        </div>


    </div>
</div>

blog/templates/components/tag-cloud.html
<div class="mb-4">
    <div class="border-bottom">
        <div class="pb-4">
            <h4 class="pb-2 fw-bold fs-14">DISCOVER MORE OF WHAT MATTERS TO YOU</h4>
            {% for tag in tags %}
                <span class="border border-dark p-1 px-3 mb-2 me-1 rounded-pill" style="display:inline-block">
                    <a class="text-decoration-none text-dark fs-15 fw-500" href="{% url 'post_by_tag' tag.slug %}">
                        {{ tag.name }}
                    </a>
                </span>
            {% endfor %}
        </div>
    </div>
</div>

templates/3-col-template.html
{% extends 'base.html' %}

{% block template %}
    <style>
        @media only screen and (min-width: 992px) {
            .col-navbar {
                flex: 0 0 80px;
                display: flex;
                justify-content: center;
                border-right: 1px solid #dee2e6;
                height: 100vh;
            }
        }


    </style>

    <div class="container" style="max-width: 1500px!important;">
        <div class="row">
            <div class="col-navbar">
                {% block content-left %}{% endblock %}
            </div>
            <div class="col-12 col-lg-8 pt-5 px-4 px-md-5">
                {% block content-mid %}{% endblock %}
            </div>
            <div class="d-none d-lg-block col-lg-3 pt-5 ps-4 border-start">
                {% include 'components/search-bar.html' %}
                {% block content-right %}{% endblock %}
                {% include 'footer.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <title>{% block title %}HomePage{% endblock %}</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/logo.jpg' %}"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"/>
    <link href="{% static "css/main.css" %}" rel="stylesheet">
    <script src="{% static 'js/htmx.min.js' %}" defer></script>
</head>
<body>


{% block template %}
{% endblock %}


<script
        src="{% static "js/bootstrap.bundle.min.js" %}"
></script>
</body>
</html>

templates/footer.html
<style>
    .footer .nav-link {
        padding: 0 10px 5px 0;
    }
    .footer a {
        color: inherit;
    }
</style>

<footer>
    <ul class="nav fw-500 fs-12 footer">
        <li class="nav-item">
            <a class="nav-link" href="#">Help</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Status</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Writers</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Blog</a>
        </li>
                <li class="nav-item">
            <a class="nav-link" href="#">Careers</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Privacy</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">Terms</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="#">About</a>
        </li>
    </ul>
</footer>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-transparent">
    <div class="container">
      <a class="navbar-brand logo fs-4" href="#">mushfiqFeed</a>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        </ul>

        <form method="get" action="search/" class="col-12 col-lg-3 mb-lg-0">
            <input type="text" name="q" class="form-control rounded-pill" placeholder="Search..." id="id_q">
        </form>
    </div>
  </div>
</nav>

templates/secondary-navbar.html
<style>
    #sm-logo-out{
        position: relative;
        background-color: black;
        width: 38px;
        height: 38px;
        top: 50%;
    }

    #sm-logo-in{
        position: relative;
        background-color: white;
        width: 12px;
        height: 12px;
        border-radius: 50%;
        top: 18%;
        left: 50%;
    }
    @media only screen and (max-width: 768px){
        .container,
        .container-sm {
            max-width: 100%;
        }
    }

</style>

<nav class="navbar navbar-expand-lg py-1 align-items-start pt-lg-4 sticky-top">
    <div class="container py-2 sticky-top">
        <a class="navbar-brand m-0" href="/">
            <div id="sm-logo-out">
                <div id="sm-logo-in">
                </div>
            </div>
        </a>
    </div>
</nav>